[mgr]
ratio = [1, 2, 3]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false
linemode = "none"
show_hidden = true
show_symlink = true
scrolloff = 5
mouse_events = ["click", "scroll"]
title_format = "Yazi: {cwd}"

[preview]
wrap = "no"
tab_size = 2
# max_width = 3840
# max_height = 2160
max_width = 600
max_height = 600
cache_dir = ""
image_delay = 30
image_filter = "nearest"       # orignal is "triangle" 
image_quality = 50
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]

[opener]
edit = [
  { run = 'nvim "$@"', desc = "Neovim", block = true, for = "unix" },
  { run = 'pinta "$@"', desc = "Edit in pinta", block = true, for = "unix" },
]
# { run = 'nvim %*', orphan = true, desc = "code", for = "windows" }, { run = 'nvim -w %*', block = true, desc = "code (block)", for = "windows" },
open = [
  { run = 'xdg-open "$1"', desc = "Open",block=false, for = "linux" },
  { run = 'xdg-open "$@"', desc = "Open", for = "macos" },
  # { run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
  # { run = 'termux-open "$1"', desc = "Open", for = "android" },
]
reveal = [
  { run = 'xdg-open "$(dirname "$1")"', desc = "Reveal", for = "linux" },
  { run = 'open -R "$1"', desc = "Reveal", for = "macos" },
  { run = 'explorer /select,"%1"', orphan = true, desc = "Reveal", for = "windows" },
  { run = 'termux-open "$(dirname "$1")"', desc = "Reveal", for = "android" },
  { run = '''clear; exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [
  { run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
  { run = 'ya pub extract --list %*', desc = "Extract here", for = "windows" },
]
play = [
  { run = 'vlc  "$@"', orphan = true, for = "unix" },
  { run = 'mpv --force-window %*', orphan = true, for = "windows" },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]


[tasks]
micro_workers = 10
macro_workers = 10
bizarre_retry = 3
image_alloc = 536870912      # 512MB
image_bound = [10000, 10000]
suppress_preload = false


[plugin]
spotters = [
  # Code
  { mime = "text/*", run = "code" },
  { mime = "application/{mbox,javascript,wine-extension-ini}", run = "code" },
  # Image
  { mime = "image/{avif,hei?,jxl}", run = "magick" },
  { mime = "image/svg+xml", run = "svg" },
  { mime = "image/*", run = "image" },
  # Video
  { mime = "video/*", run = "video" },
  # Fallback
  { name = "*", run = "file" },
]
preloaders = [
  # Child Folders
  { name = "*/", run = "folder" },
  # Image
  { mime = "image/{avif,hei?,jxl}", run = "magick" },
  { mime = "image/svg+xml", run = "svg" },
  { mime = "image/*", run = "image" },
  # Video
  { mime = "video/*", run = "video" },
  # PDF
  { mime = "application/pdf", run = "pdf" },
  # Font
  { mime = "font/*", run = "font" },
  { mime = "application/ms-opentype", run = "font" },
]
# Y: this fucks showign child directories in 3rd pain.
#
# previewers = [
#   { name = "*/", run = "folder" },
#   # Code
#   { mime = "text/*", run = "code" },
#   { mime = "application/{mbox,javascript,wine-extension-ini}", run = "code" },
#   # JSON
#   { mime = "application/{json,ndjson}", run = "json" },
#   # Image
#   { mime = "image/{avif,hei?,jxl}", run = "magick" },
#   { mime = "image/svg+xml", run = "svg" },
#   { mime = "image/*", run = "image" },
#   # Video
#   { mime = "video/*", run = "video" },
#   # PDF
#   { mime = "application/pdf", run = "pdf" },
#   # Archive
#   { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", run = "archive" },
#   { mime = "application/{debian*-package,redhat-package-manager,rpm,android.package-archive}", run = "archive" },
#   { name = "*.{AppImage,appimage}", run = "archive" },
#   # Virtual Disk / Disk Image
#   { mime = "application/{iso9660-image,qemu-disk,ms-wim,apple-diskimage}", run = "archive" },
#   { mime = "application/virtualbox-{vhd,vhdx}", run = "archive" },
#   # { name = "*.{img,fat,ext,ext2,ext3,ext4,squashfs,ntfs,hfs,hfsx}", run = "archive" },
#   # Font
#   { mime = "font/*", run = "font" },
#   { mime = "application/ms-opentype", run = "font" },
#   # Empty file
#   { mime = "inode/empty", run = "empty" },
#   # Fallback
#   { name = "*", run = "file" },
# ]

# B: 3rd party plugins 
# GIT
[[plugin.prepend_fetchers]]
id  = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id  = "git"
url = "*/"
run = "git"

# B: djvu-LibreOffice=Docmuents preview
