
# BUNNY
[[mgr.prepend_keymap]]
on = ";"
run = "plugin bunny"
desc = "Start bunny.yazi"

# GVFS
[[mgr.prepend_keymap]]
on = ["M", "m"]
run = "plugin gvfs -- select-then-mount"
desc = "Select device then mount"

[[mgr.prepend_keymap]]
on = ["M", "u"]
run = "plugin gvfs -- select-then-unmount"
desc = "Select device then unmount"

[[mgr.prepend_keymap]]
on = ["M", "E"]
run = "plugin gvfs -- select-then-unmount --eject"
desc = "Eject device"

[[mgr.prepend_keymap]]
on = ["g", "m"]
run = "plugin gvfs -- jump-to-device"
desc = "Jump to device mount point"

[[mgr.prepend_keymap]]
on = ["`", "`"]
run = "plugin gvfs -- jump-back-prev-cwd"
desc = "Jump back to previous cwd"
